"""initial_schema

Revision ID: bb9ee5c97806
Revises: 
Create Date: 2026-07-17 12:09:47.640946
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb9ee5c97806'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('segment', sa.String(length=150), nullable=False),
    sa.Column('region', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code', name='uq_customer_master_code')
    )
    op.create_index(op.f('ix_customer_master_created_at'), 'customer_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_master_is_deleted'), 'customer_master', ['is_deleted'], unique=False)
    op.create_index('ix_customer_master_name', 'customer_master', ['customer_name'], unique=False)
    op.create_index('ix_customer_master_segment', 'customer_master', ['segment'], unique=False)
    op.create_table('distributors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_distributors_company', 'distributors', ['company'], unique=False)
    op.create_index(op.f('ix_distributors_created_at'), 'distributors', ['created_at'], unique=False)
    op.create_index('ix_distributors_email', 'distributors', ['email'], unique=False)
    op.create_index('ix_distributors_email_active', 'distributors', ['email'], unique=True, postgresql_where='is_deleted = false AND email IS NOT NULL')
    op.create_index(op.f('ix_distributors_is_deleted'), 'distributors', ['is_deleted'], unique=False)
    op.create_index('ix_distributors_name', 'distributors', ['name'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('graph_message_id', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('internet_message_id', sa.String(length=500), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('process_status', sa.String(length=50), server_default='unread', nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('mailbox', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_message_id', name='uq_email_messages_graph_id')
    )
    op.create_index(op.f('ix_email_messages_created_at'), 'email_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_messages_is_deleted'), 'email_messages', ['is_deleted'], unique=False)
    op.create_index('ix_email_messages_is_read', 'email_messages', ['is_read'], unique=False)
    op.create_index('ix_email_messages_process_status', 'email_messages', ['process_status'], unique=False)
    op.create_index('ix_email_messages_received_at', 'email_messages', ['received_at'], unique=False)
    op.create_index('ix_email_messages_sender_email', 'email_messages', ['sender_email'], unique=False)
    op.create_table('product_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('segment', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), server_default='KG', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code', name='uq_product_master_code')
    )
    op.create_index(op.f('ix_product_master_created_at'), 'product_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_master_is_deleted'), 'product_master', ['is_deleted'], unique=False)
    op.create_index('ix_product_master_name', 'product_master', ['product_name'], unique=False)
    op.create_index('ix_product_master_segment', 'product_master', ['segment'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=50), server_default='started', nullable=False),
    sa.Column('mailbox', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emails_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('emails_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attachments_downloaded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reports_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_created_at'), 'sync_jobs', ['created_at'], unique=False)
    op.create_index('ix_sync_jobs_started_at', 'sync_jobs', ['started_at'], unique=False)
    op.create_index('ix_sync_jobs_status', 'sync_jobs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index('ix_users_email_active', 'users', ['email'], unique=True, postgresql_where='is_deleted = false')
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_trail_action', 'audit_trail', ['action'], unique=False)
    op.create_index('ix_audit_trail_created_at', 'audit_trail', ['created_at'], unique=False)
    op.create_index('ix_audit_trail_entity_type', 'audit_trail', ['entity_type'], unique=False)
    op.create_index('ix_audit_trail_report_name', 'audit_trail', ['report_name'], unique=False)
    op.create_index('ix_audit_trail_user_id', 'audit_trail', ['user_id'], unique=False)
    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('graph_attachment_id', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('is_excel', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_attachment_id', name='uq_email_attachments_graph_id')
    )
    op.create_index(op.f('ix_email_attachments_created_at'), 'email_attachments', ['created_at'], unique=False)
    op.create_index('ix_email_attachments_email_message_id', 'email_attachments', ['email_message_id'], unique=False)
    op.create_index('ix_email_attachments_file_name', 'email_attachments', ['file_name'], unique=False)
    op.create_index(op.f('ix_email_attachments_is_deleted'), 'email_attachments', ['is_deleted'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=100), server_default='Sales Report', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('source', sa.String(length=50), server_default='upload', nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('distributor_id', sa.Integer(), nullable=True),
    sa.Column('email_message_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_reports_content_hash')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index('ix_reports_distributor_id', 'reports', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_reports_is_deleted'), 'reports', ['is_deleted'], unique=False)
    op.create_index('ix_reports_period', 'reports', ['period'], unique=False)
    op.create_index(op.f('ix_reports_public_id'), 'reports', ['public_id'], unique=True)
    op.create_index('ix_reports_report_date', 'reports', ['report_date'], unique=False)
    op.create_index('ix_reports_source', 'reports', ['source'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_reports_type', 'reports', ['report_type'], unique=False)
    op.create_table('sales_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sr_no', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('segment', sa.String(length=150), nullable=False),
    sa.Column('product', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('quantity_display', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='KG', nullable=False),
    sa.Column('row_hash', sa.String(length=128), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'row_hash', name='uq_sales_records_report_row_hash')
    )
    op.create_index(op.f('ix_sales_records_created_at'), 'sales_records', ['created_at'], unique=False)
    op.create_index('ix_sales_records_customer_name', 'sales_records', ['customer_name'], unique=False)
    op.create_index('ix_sales_records_distributor_id', 'sales_records', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_sales_records_is_deleted'), 'sales_records', ['is_deleted'], unique=False)
    op.create_index('ix_sales_records_period', 'sales_records', ['period'], unique=False)
    op.create_index('ix_sales_records_product', 'sales_records', ['product'], unique=False)
    op.create_index('ix_sales_records_report_id', 'sales_records', ['report_id'], unique=False)
    op.create_index('ix_sales_records_segment', 'sales_records', ['segment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_records_segment', table_name='sales_records')
    op.drop_index('ix_sales_records_report_id', table_name='sales_records')
    op.drop_index('ix_sales_records_product', table_name='sales_records')
    op.drop_index('ix_sales_records_period', table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_is_deleted'), table_name='sales_records')
    op.drop_index('ix_sales_records_distributor_id', table_name='sales_records')
    op.drop_index('ix_sales_records_customer_name', table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_created_at'), table_name='sales_records')
    op.drop_table('sales_records')
    op.drop_index('ix_reports_type', table_name='reports')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_source', table_name='reports')
    op.drop_index('ix_reports_report_date', table_name='reports')
    op.drop_index(op.f('ix_reports_public_id'), table_name='reports')
    op.drop_index('ix_reports_period', table_name='reports')
    op.drop_index(op.f('ix_reports_is_deleted'), table_name='reports')
    op.drop_index('ix_reports_distributor_id', table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_email_attachments_is_deleted'), table_name='email_attachments')
    op.drop_index('ix_email_attachments_file_name', table_name='email_attachments')
    op.drop_index('ix_email_attachments_email_message_id', table_name='email_attachments')
    op.drop_index(op.f('ix_email_attachments_created_at'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_index('ix_audit_trail_user_id', table_name='audit_trail')
    op.drop_index('ix_audit_trail_report_name', table_name='audit_trail')
    op.drop_index('ix_audit_trail_entity_type', table_name='audit_trail')
    op.drop_index('ix_audit_trail_created_at', table_name='audit_trail')
    op.drop_index('ix_audit_trail_action', table_name='audit_trail')
    op.drop_table('audit_trail')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sync_jobs_status', table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_started_at', table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_created_at'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index('ix_product_master_segment', table_name='product_master')
    op.drop_index('ix_product_master_name', table_name='product_master')
    op.drop_index(op.f('ix_product_master_is_deleted'), table_name='product_master')
    op.drop_index(op.f('ix_product_master_created_at'), table_name='product_master')
    op.drop_table('product_master')
    op.drop_index('ix_email_messages_sender_email', table_name='email_messages')
    op.drop_index('ix_email_messages_received_at', table_name='email_messages')
    op.drop_index('ix_email_messages_process_status', table_name='email_messages')
    op.drop_index('ix_email_messages_is_read', table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_is_deleted'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_created_at'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index('ix_distributors_name', table_name='distributors')
    op.drop_index(op.f('ix_distributors_is_deleted'), table_name='distributors')
    op.drop_index('ix_distributors_email_active', table_name='distributors', postgresql_where='is_deleted = false AND email IS NOT NULL')
    op.drop_index('ix_distributors_email', table_name='distributors')
    op.drop_index(op.f('ix_distributors_created_at'), table_name='distributors')
    op.drop_index('ix_distributors_company', table_name='distributors')
    op.drop_table('distributors')
    op.drop_index('ix_customer_master_segment', table_name='customer_master')
    op.drop_index('ix_customer_master_name', table_name='customer_master')
    op.drop_index(op.f('ix_customer_master_is_deleted'), table_name='customer_master')
    op.drop_index(op.f('ix_customer_master_created_at'), table_name='customer_master')
    op.drop_table('customer_master')
    # ### end Alembic commands ###
